excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BobBall.github.io
title: BobBallSite
email: 
author: Bob Ball
description: My awesome new site
paginate: 6
google_analytics: 